services:
  proxcenter:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxcenter
    ports:
      - "3000:3000"
    environment:
      PROXMOXCENTER_CLOUD_OAUTH_MODE: local
    volumes:
      - ./data:/app/data
    restart: unless-stopped
